-- SQL Schema to initialize TalentGraph on Supabase
-- Run this inside the Supabase SQL Editor (https://supabase.com)

-- 1. Create Employees Table
CREATE TABLE IF NOT EXISTS employees (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  department TEXT NOT NULL,
  role TEXT NOT NULL,
  "experienceYears" INTEGER NOT NULL,
  "performanceRating" DOUBLE PRECISION NOT NULL,
  "technicalSkills" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "softSkills" JSONB NOT NULL DEFAULT '[]'::jsonb,
  certifications JSONB NOT NULL DEFAULT '[]'::jsonb,
  "resumeText" TEXT,
  "currentProjects" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "profileSummary" TEXT NOT NULL
);

-- 2. Create Projects Table
CREATE TABLE IF NOT EXISTS projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  "requiredSkills" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "teamSize" INTEGER NOT NULL,
  "durationMonths" INTEGER NOT NULL
);

-- 3. Create Learning Recommendations Table
CREATE TABLE IF NOT EXISTS learning_recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employeeId" TEXT REFERENCES employees(id) ON DELETE CASCADE,
  "courseName" TEXT NOT NULL,
  type TEXT NOT NULL,
  roadmap JSONB NOT NULL DEFAULT '[]'::jsonb,
  timeline TEXT NOT NULL,
  description TEXT NOT NULL
);

-- 4. Create Promotion Evaluations Table
CREATE TABLE IF NOT EXISTS promotion_evaluations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employeeId" TEXT UNIQUE REFERENCES employees(id) ON DELETE CASCADE,
  "promotionScore" INTEGER NOT NULL,
  reasoning TEXT NOT NULL,
  "areasToImprove" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "evaluatedAt" TEXT NOT NULL
);

-- Enable Row Level Security (RLS) or leave public for development
-- For development simplicity, we can keep the tables public or add basic select access
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotion_evaluations ENABLE ROW LEVEL SECURITY;

-- Create policies allowing full access (development bypass)
CREATE POLICY "Allow public read" ON employees FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON employees FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON employees FOR UPDATE USING (true);

CREATE POLICY "Allow public read" ON projects FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON projects FOR UPDATE USING (true);

CREATE POLICY "Allow public read" ON learning_recommendations FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON learning_recommendations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON learning_recommendations FOR UPDATE USING (true);

CREATE POLICY "Allow public read" ON promotion_evaluations FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON promotion_evaluations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON promotion_evaluations FOR UPDATE USING (true);
