-- SQL Migrations for Enterprise Project Management & Health Engine
-- Run this inside the Supabase SQL Editor (https://supabase.com)

-- 1. Alter Projects Table to add new details
ALTER TABLE projects
ADD COLUMN IF NOT EXISTS "client" TEXT,
ADD COLUMN IF NOT EXISTS "industry" TEXT,
ADD COLUMN IF NOT EXISTS "businessUnit" TEXT,
ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'Planning',
ADD COLUMN IF NOT EXISTS "budget" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "currency" TEXT DEFAULT 'USD',
ADD COLUMN IF NOT EXISTS "startDate" TEXT,
ADD COLUMN IF NOT EXISTS "endDate" TEXT,
ADD COLUMN IF NOT EXISTS "expectedDelivery" TEXT,
ADD COLUMN IF NOT EXISTS "projectManager" TEXT,
ADD COLUMN IF NOT EXISTS "deliveryLead" TEXT,
ADD COLUMN IF NOT EXISTS "technicalLead" TEXT,
ADD COLUMN IF NOT EXISTS "projectCode" TEXT,
ADD COLUMN IF NOT EXISTS "tags" JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "healthScore" DOUBLE PRECISION DEFAULT 100.0,
ADD COLUMN IF NOT EXISTS "healthLevel" TEXT DEFAULT 'Excellent',
ADD COLUMN IF NOT EXISTS "healthExplanation" TEXT,
ADD COLUMN IF NOT EXISTS "healthTrendWeek" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "healthTrendMonth" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "deliveryConfidence" DOUBLE PRECISION DEFAULT 100.0,
ADD COLUMN IF NOT EXISTS "onTimeProbability" DOUBLE PRECISION DEFAULT 100.0,
ADD COLUMN IF NOT EXISTS "budgetOverrunProbability" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "estimatedCompletionDate" TEXT;

-- 2. Create Project Members Table
CREATE TABLE IF NOT EXISTS project_members (
  id TEXT PRIMARY KEY,
  "projectId" TEXT REFERENCES projects(id) ON DELETE CASCADE,
  "employeeId" TEXT REFERENCES employees(id) ON DELETE CASCADE,
  "role" TEXT NOT NULL,
  "skillMatch" DOUBLE PRECISION DEFAULT 100.0,
  "allocation" DOUBLE PRECISION DEFAULT 100.0,
  "performance" DOUBLE PRECISION DEFAULT 5.0,
  "availability" TEXT DEFAULT 'Available'
);

-- 3. Create Project Tasks Table
CREATE TABLE IF NOT EXISTS project_tasks (
  id TEXT PRIMARY KEY,
  "projectId" TEXT REFERENCES projects(id) ON DELETE CASCADE,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "status" TEXT NOT NULL, -- 'Pending', 'In Progress', 'Completed'
  "assigneeId" TEXT REFERENCES employees(id) ON DELETE SET NULL,
  "dueDate" TEXT,
  "priority" TEXT -- 'High', 'Medium', 'Low'
);

-- 4. Create Project Milestones Table
CREATE TABLE IF NOT EXISTS project_milestones (
  id TEXT PRIMARY KEY,
  "projectId" TEXT REFERENCES projects(id) ON DELETE CASCADE,
  "name" TEXT NOT NULL,
  "ownerId" TEXT REFERENCES employees(id) ON DELETE SET NULL,
  "dueDate" TEXT,
  "status" TEXT NOT NULL, -- 'Planning', 'Design', 'Development', 'Testing', 'Deployment', 'Maintenance'
  "dependencies" JSONB DEFAULT '[]'::jsonb
);

-- 5. Create Project Documents Table
CREATE TABLE IF NOT EXISTS project_documents (
  id TEXT PRIMARY KEY,
  "projectId" TEXT REFERENCES projects(id) ON DELETE CASCADE,
  "name" TEXT NOT NULL,
  "url" TEXT,
  "type" TEXT, -- 'Overview', 'Team', 'Milestones', 'Documents', 'Meeting Notes', 'Architecture', 'Risks', 'Activity'
  "uploadedAt" TEXT,
  "uploadedBy" TEXT
);

-- 6. Create Project Activity Table
CREATE TABLE IF NOT EXISTS project_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "projectId" TEXT REFERENCES projects(id) ON DELETE CASCADE,
  "description" TEXT NOT NULL,
  "userId" TEXT,
  "timestamp" TEXT NOT NULL
);

-- 7. Create Project Risks Table
CREATE TABLE IF NOT EXISTS project_risks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "projectId" TEXT REFERENCES projects(id) ON DELETE CASCADE,
  "type" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "severity" TEXT NOT NULL, -- 'Low', 'Medium', 'High', 'Critical'
  "recommendation" TEXT NOT NULL,
  "expectedImprovement" TEXT NOT NULL
);

-- Enable RLS for all tables
ALTER TABLE project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_risks ENABLE ROW LEVEL SECURITY;

-- Add bypass policies for development
CREATE POLICY "Allow public read" ON project_members FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON project_members FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON project_members FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON project_members FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON project_tasks FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON project_tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON project_tasks FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON project_tasks FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON project_milestones FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON project_milestones FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON project_milestones FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON project_milestones FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON project_documents FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON project_documents FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON project_documents FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON project_documents FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON project_activity FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON project_activity FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON project_activity FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON project_activity FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON project_risks FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON project_risks FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON project_risks FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON project_risks FOR DELETE USING (true);
