-- SQL Migrations for AI Talent Intelligence Features
-- Run this inside the Supabase SQL Editor (https://supabase.com)

-- 1. Enable pgvector extension for Semantic Skill Matching
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Modify Employees Table
-- Add new columns for Risk Detection, Attrition Prediction, etc.
ALTER TABLE employees
ADD COLUMN IF NOT EXISTS "flightRiskScore" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "engagementIndex" DOUBLE PRECISION DEFAULT 100.0,
ADD COLUMN IF NOT EXISTS "promotionDate" TEXT,
ADD COLUMN IF NOT EXISTS "lastReviewDate" TEXT,
ADD COLUMN IF NOT EXISTS "resume_embedding" vector(1536);

-- Create an HNSW index for the embedding to speed up similarity search
CREATE INDEX IF NOT EXISTS employees_resume_embedding_idx ON employees USING hnsw (resume_embedding vector_cosine_ops);

-- 3. Create Audit Logs Table for Tracking Behavior
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employeeId" TEXT REFERENCES employees(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  "timestamp" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON audit_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON audit_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON audit_logs FOR UPDATE USING (true);

-- 4. Create RPC function for Semantic Search Match
CREATE OR REPLACE FUNCTION match_skills (
  query_embedding vector(1536),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id text,
  name text,
  role text,
  department text,
  similarity float
)
LANGUAGE sql STABLE
AS $$
  select
    employees.id,
    employees.name,
    employees.role,
    employees.department,
    1 - (employees.resume_embedding <=> query_embedding) as similarity
  from employees
  where 1 - (employees.resume_embedding <=> query_embedding) > match_threshold
  order by similarity desc
  limit match_count;
$$;
